name: Generate blacklist

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  
jobs:
  publish:

    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt
    - name: Generate blacklist
      run: python processor.py
    - name: Publish package
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "*.rsc"
        makeLatest: true
        tag: "latest"
